export const SET_USERS = "SET_USERS"
export const GET_USERS = "GET_USERS"
export const SET_ACTIVITIES = "GET_ACTIVITIES"
export const CHANGE_ACTIONS = "CHANGE_ACTIONS"
export const SET_COMPLAINTS = "SET_COMPLAINTS"
export const SET_VALUABLES = 'SET_VALUABLES'
export const SHOW_TOAST = 'SHOW_TOAST'
export const HIDE_TOAST =  'HIDE_TOAST'